import type { Metadata } from "next";
import { ThemeProvider } from "next-themes"
import { Space_Grotesk } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Space_Grotesk({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};  

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  const messages = await getMessages({ locale })
  return (
    <html
      lang={locale}
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute={'class'}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar/>
              {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
